shade_venv: bump setuptools to 17.1
Based on pbr docs
https://docs.openstack.org/pbr/latest/user/compatibility.html#evaluate-marker
projects which use '>', '<' ... and similar markers need setuptools at
least 17.1.
Since we already have 17.0 there, it seems as small update
given that there is no record why 17.0 was original selected at all.

This issue appears as:

> fatal: [hypervisor]: FAILED! => {"changed": false, "cmd":
>   "/var/tmp/venv_shade/bin/pip install setuptools==17.0 pytz==2016.4
>    shade==1.25.0 pip==9.0.1"
> ....
> Downloading/unpacking shade==1.25.0
>   Running setup.py egg_info for package shade
>
>     Installed /var/tmp/venv_shade/build/shade/pbr-3.1.1-py2.7.egg
>     Marker evaluation failed, see the following error.  For more information see: http://docs.openstack.org/developer/pbr/compatibility.html#evaluate-marker
>     ERROR:root:Error parsing
>     Traceback (most recent call last):
>     ...
>       File \"/var/tmp/venv_shade/lib/python2.7/site-packages/pkg_resources.py\", line 1324, in comparison
>         raise SyntaxError(repr(cop)+\" operator not allowed in environment markers\")
>     SyntaxError: '<' operator not allowed in environment markers
>     error in setup command: Error parsing /var/tmp/venv_shade/build/shade/setup.cfg: SyntaxError: '<' operator not allowed in environment markers
>     Complete output from command python setup.py egg_info:
>
>
> Installed /var/tmp/venv_shade/build/shade/pbr-3.1.1-py2.7.egg
>
> Marker evaluation failed, see the following error.  For more information see: http://docs.openstack.org/developer/pbr/compatibility.html#evaluate-marker
>
> ERROR:root:Error parsing

(btw 17.0 seems to originate from InfraRed # 9a9e24b6444c139883722f7c7db9911fdc13903d when ooo-oc was added)

Change-Id: I54a53786988a35ddf99ddc65134d02447df46698